matrix:
  include:
    - language: elixir
      elixir: "1.6"
      otp_release: "20.0"
      before_script:
        - MIX_ENV=test mix compile
        - MIX_ENV=test mix ecto.create
      script:
        - mix test

cache:
  directories:
    - _build
    - deps
